import {test,expect} from '@playwright/test';
test('extensión bloqueada no guarda nada y agrega las dos clases después de resolver',async({page})=>{
 await page.goto('/');await page.locator('.demo-controls summary').click();await page.getByLabel('Escenario',{exact:true}).selectOption('calendar');await page.getByRole('button',{name:'Aplicar escenario y reiniciar'}).click();await page.getByLabel('Correo electrónico').fill('admin@demo.local');await page.getByLabel('Contraseña',{exact:true}).fill('Aulas2026');await page.getByRole('button',{name:'Ingresar',exact:true}).click();
 async function route(path:string){await page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);}
 await route('/administracion/calendario');await page.getByLabel('Fin 2',{exact:true}).fill('2026-12-23');await page.getByRole('button',{name:'Revisar impacto'}).click();await expect(page.getByRole('alert')).toContainText('R-BLOCK');await expect(page.getByRole('button',{name:'Confirmar cambio de calendario'})).toHaveCount(0);
 await route('/reservas/R-MAT');await expect(page.getByRole('heading',{name:'26 clases registradas'})).toBeVisible();await route('/administracion/calendario');await expect(page.getByLabel('Fin 2',{exact:true})).toHaveValue('2026-12-18');
 await route('/reservas/R-BLOCK');await page.getByRole('button',{name:'Cancelar clases',exact:true}).click();await page.getByRole('checkbox').check();await page.getByLabel('Motivo de cancelación').fill('Resolución para ampliar el cuatrimestre');await page.getByRole('button',{name:'Confirmar cancelación'}).click();
 await route('/administracion/calendario');await page.getByLabel('Fin 2',{exact:true}).fill('2026-12-23');await page.getByRole('button',{name:'Revisar impacto'}).click();await expect(page.getByText(/Clases nuevas: 2/)).toBeVisible();await page.getByRole('button',{name:'Confirmar cambio de calendario'}).click();await expect(page.getByRole('status')).toContainText('Calendario y clases actualizados');
 await route('/reservas/R-MAT');await expect(page.getByRole('heading',{name:'28 clases registradas'})).toBeVisible();await expect(page.locator('.booking-occurrences article').filter({hasText:'21 de diciembre de 2026'})).toContainText('Aula 203');await expect(page.locator('.booking-occurrences article').filter({hasText:'23 de diciembre de 2026'})).toContainText('Aula 105');
 await route('/agenda');await page.getByLabel('Fecha de agenda').fill('2026-12-23');await expect(page.locator('.booking').filter({hasText:'Matemática I'})).toHaveCount(1);await expect(page.locator('.booking').filter({hasText:'Física I'})).toHaveCount(0);
 await route('/indicadores');await page.getByLabel('Día',{exact:true}).fill('2026-12-23');await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('2 h');await expect(page.getByText('60',{exact:true})).toBeVisible();
});
