import {test,expect} from '@playwright/test';
test('modificar, trasladar y cancelar mantienen agenda, listados, detalle e indicadores coherentes',async({page})=>{
 await page.goto('/');await page.getByLabel('Correo electrónico').fill('bedel@demo.local');await page.getByLabel('Contraseña',{exact:true}).fill('Aulas2026');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await page.getByLabel('Fecha de agenda').fill('2026-09-14');
 await page.locator('.booking').filter({hasText:'Física I'}).click();await page.getByRole('button',{name:'Modificar datos',exact:true}).click();await page.getByLabel('Alumnos previstos',{exact:true}).fill('30');await page.getByRole('button',{name:'Guardar datos'}).click();
 await page.getByRole('button',{name:'Cambiar aula',exact:true}).click();await page.getByRole('radio',{name:/Aula 301/}).check();await page.getByRole('button',{name:'Guardar cambio de aula'}).click();
 await page.getByRole('link',{name:'Indicadores',exact:true}).click();await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('6,5 h');await expect(page.getByText('243',{exact:true})).toBeVisible();
 async function route(path:string){await page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);}
 await route('/reservas/R-002');await page.getByRole('button',{name:'Reprogramar clases',exact:true}).click();await page.getByRole('checkbox').check();await page.getByLabel('Nueva fecha',{exact:true}).fill('2026-09-15');await page.getByRole('button',{name:'Revisar reprogramación'}).click();await page.getByRole('button',{name:'Guardar reprogramación'}).click();
 await expect(page.locator('.booking-occurrences')).toContainText('15 de septiembre de 2026');await expect(page.locator('.booking-occurrences')).toContainText('Aula 301');
 await route('/agenda');await expect(page.locator('.booking').filter({hasText:'Física I'})).toHaveCount(0);await page.getByLabel('Fecha de agenda').fill('2026-09-15');await expect(page.locator('.booking').filter({hasText:'Física I'})).toHaveCount(1);
 await route('/reservas');await expect(page.locator('.screen-list tbody tr').filter({hasText:'Física I'})).toHaveCount(0);await page.getByLabel('Fecha del listado').fill('2026-09-15');await expect(page.locator('.screen-list tbody tr')).toHaveCount(1);await expect(page.locator('.screen-list tbody')).toContainText('301');
 await route('/indicadores');await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('5 h');await expect(page.getByText('198',{exact:true})).toBeVisible();await page.getByLabel('Día',{exact:true}).fill('2026-09-15');await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('1,5 h');await expect(page.getByText('45',{exact:true})).toBeVisible();
 await route('/reservas/R-002');await page.getByRole('button',{name:'Cancelar clases',exact:true}).click();await page.getByRole('checkbox').check();await page.getByLabel('Motivo de cancelación').fill('Clase suspendida');await page.getByRole('button',{name:'Confirmar cancelación'}).click();await expect(page.locator('.booking-occurrences')).toContainText('Cancelada');
 await route('/agenda');await expect(page.locator('.booking').filter({hasText:'Física I'})).toHaveCount(0);
 await route('/reservas');await page.getByLabel('Fecha del listado').fill('2026-09-15');await expect(page.locator('.screen-list tbody tr')).toHaveCount(0);await page.getByLabel('Estado del listado').selectOption('cancelled');await expect(page.locator('.screen-list tbody tr')).toHaveCount(1);await expect(page.locator('.screen-list tbody')).toContainText('Física I');
 await route('/indicadores');await page.getByLabel('Día',{exact:true}).fill('2026-09-15');await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('0 h');await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('0 %');await page.screenshot({path:'evidence/consistencia-cancelacion.png',fullPage:true});
});
