import { test, expect } from '@playwright/test'
async function login(page: import('@playwright/test').Page, role = 'bedel') {
  await page.goto('/')
  await page.getByLabel('Correo electrónico').fill(`${role}@demo.local`)
  await page.getByLabel('Contraseña', { exact: true }).fill('Aulas2026')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
}
test('reserva periódica completa y lectura desde agenda', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await login(page)
  await page.screenshot({ path: 'evidence/agenda-desktop.png' })
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.screenshot({ path: 'evidence/reserva-desktop.png', fullPage: true, animations: "disabled" })
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  const monday = page.getByRole('group', { name: /Lunes/ })
  await expect(monday.getByText('Aula 105', { exact: true })).toHaveCount(0)
  await monday.getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Volver', exact: true }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(monday.getByRole('radio').first()).toBeChecked()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Volver', exact: true }).click()
  await expect(monday.getByRole('radio').first()).toBeChecked()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await expect(page.getByRole('heading', { name: 'Reserva confirmada' })).toBeVisible()
  await page.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByRole('heading', { name: '26 clases registradas' })).toBeVisible()
  await page.getByRole('link', { name: 'Agenda', exact: true }).click()
  await expect(page.getByRole('button', { name: /Matemática I/ }).first()).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/agenda-mobile.png', fullPage: true, animations: "disabled" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
test('docente consulta y no accede a nueva reserva', async ({ page }) => {
  await login(page, 'docente')
  await expect(page.getByRole('button', { name: 'Nueva reserva' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Reservas', exact: true }).click()
  await page.getByRole('button', { name: /Historia/ }).click()
  await expect(page.getByRole('heading', { name: 'Historia', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page.getByRole('heading', { name: 'Ingresar' })).toBeVisible()
})
test('formulario en móvil y tablet no desborda', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  for (const width of [390, 768]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/reserva-mobile.png', fullPage: true, animations: "disabled" })
})
test('excluir una fecha mantiene aula por patrón y guarda 25 clases', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByText('Revisar fechas y exclusiones', { exact: true }).click()
  await page.getByLabel('14 de septiembre de 2026 · 14:00–16:00', { exact: true }).uncheck()
  await expect(page.getByText('14 de septiembre de 2026 · Exclusión manual')).toBeVisible()
  await page.screenshot({ path: 'evidence/exclusiones-desktop.png', fullPage: true, animations: "disabled" })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/exclusiones-mobile.png', fullPage: true, animations: "disabled" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await page.getByRole('group', { name: /Lunes/ }).getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await page.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByRole('heading', { name: '25 clases registradas' })).toBeVisible()
})
test('período terminado bloquea el avance sin borrar la preparación', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByLabel('Período', { exact: true }).selectOption('first')
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(page.getByRole('alert')).toContainText('al menos una clase futura')
  await page.getByLabel('Período', { exact: true }).selectOption('annual')
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(page.getByRole('heading', { name: 'Un aula para cada día semanal' })).toBeVisible()
})
test('conflictos son informativos y no permiten elegir el aula ocupada', async ({ page }) => {
 await login(page)
 await page.getByRole('button', { name: 'Nueva reserva' }).click()
 await page.getByLabel('Tipo de aula').selectOption('General')
 await page.getByRole('button', { name: 'Buscar aulas' }).click()
 const monday = page.getByRole('group', {name:/Lunes/})
 await expect(monday.getByRole('heading',{name:'Requieren resolver conflictos'})).toBeVisible()
 await expect(monday.getByRole('radio')).toHaveCount(0)
 await monday.getByText('Ver reservas y contactos').click()
 await expect(monday.getByText(/sofia.paz@example.test/)).toBeVisible()
 await expect(monday.getByText(/bedel@demo.local/)).toBeVisible()
 await page.screenshot({path:'evidence/conflictos-desktop.png',fullPage:true,animations:"disabled"})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/conflictos-mobile.png',fullPage:true,animations:"disabled"})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('group',{name:/Miércoles/}).getByRole('radio').first().check()
 await expect(page.getByRole('button',{name:'Revisar reserva'})).toBeDisabled()
 await expect(page.getByRole('button',{name:'Confirmar reserva'})).toHaveCount(0)
})

test('conservar cuarta aula al contraer y volver de revisión', async ({ page }) => {
 await login(page)
 await page.getByRole('button', {name:'Nueva reserva'}).click()
 await page.getByRole('button', {name:'Buscar aulas'}).click()
 await page.getByRole('group',{name:/Lunes/}).getByRole('radio').first().check()
 const wed = page.getByRole('group',{name:/Miércoles/})
 await wed.getByRole('button',{name:'Ver todas (4)'}).click()
 await wed.getByRole('radio',{name:/Aula 204/}).check()
 await wed.getByRole('button',{name:'Ver primeras tres'}).click()
 await expect(wed.getByRole('radio',{name:/Aula 204/})).toBeChecked()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await page.getByRole('button',{name:'Volver',exact:true}).click()
 await expect(wed.getByRole('radio',{name:/Aula 204/})).toBeChecked()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await expect(page.getByRole('button',{name:'Confirmar reserva'})).toBeVisible()
})
test('crear comisión reutiliza materia y recursos filtran aulas', async ({page})=>{
 await login(page)
 await page.getByRole('button',{name:'Nueva reserva'}).click()
 await page.getByRole('button',{name:'Crear curso',exact:true}).click()
 await page.getByLabel('Nombre de materia').fill('  matemática   i ')
 await page.getByLabel('Comisión',{exact:true}).fill('b')
 await page.getByRole('button',{name:'Guardar curso y seleccionar'}).click()
 await expect(page.getByLabel('Curso',{exact:true})).toHaveValue('001-B-2026')
 await page.getByLabel('Proyector',{exact:true}).check()
 await page.screenshot({path:'evidence/catalogo-desktop.png',fullPage:true,animations:"disabled"})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/catalogo-mobile.png',fullPage:true,animations:"disabled"})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Buscar aulas'}).click()
 await expect(page.getByText('Aula 204',{exact:true})).toHaveCount(0)
 await page.getByRole('group',{name:/Lunes/}).getByRole('radio').first().check()
 await page.getByRole('group',{name:/Miércoles/}).getByRole('radio').first().check()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await page.getByRole('button',{name:'Confirmar reserva'}).click()
 await page.getByRole('button',{name:'Ver detalle'}).click()
 await expect(page.getByText(/001-B-2026/)).toBeVisible()
})
test('esporádica registra dos fechas con aulas distintas', async ({page})=>{
 await login(page)
 await page.getByRole('button',{name:'Nueva reserva'}).click()
 await page.getByRole('button',{name:'Esporádica',exact:true}).click()
 await page.screenshot({path:'evidence/esporadica-desktop.png',fullPage:true,animations:"disabled"})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/esporadica-mobile.png',fullPage:true,animations:"disabled"})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Buscar aulas'}).click()
 const first=page.getByRole('group',{name:/14 de septiembre/})
 const second=page.getByRole('group',{name:/21 de septiembre/})
 await first.getByRole('radio',{name:/Aula 203/}).check()
 await second.getByRole('radio',{name:/Aula 105/}).check()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await page.getByRole('button',{name:'Volver',exact:true}).click()
 await expect(first.getByRole('radio',{name:/Aula 203/})).toBeChecked()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await page.getByRole('button',{name:'Confirmar reserva'}).click()
 await page.getByRole('button',{name:'Ver detalle'}).click()
 await expect(page.getByRole('heading',{name:'2 clases registradas'})).toBeVisible()
 await expect(page.getByText('Aula 203',{exact:true})).toBeVisible()
 await expect(page.getByText('Aula 105',{exact:true})).toBeVisible()
})
test('consulta docente oculta contactos y registro',async({page})=>{
 await login(page,'docente')
 await page.getByRole('link',{name:'Disponibilidad',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Disponibilidad de aulas'})).toBeVisible()
 await expect(page.getByLabel('Curso',{exact:true})).toHaveCount(0)
 await page.getByLabel('Tipo de aula').selectOption('General')
 await page.getByRole('button',{name:'Buscar aulas'}).click()
 await page.getByText('Ver reservas',{exact:true}).click()
 await expect(page.getByText(/sofia.paz@example.test/)).toHaveCount(0)
 await expect(page.getByText(/bedel@demo.local/)).toHaveCount(0)
 await expect(page.getByRole('radio')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Preparar reserva'})).toHaveCount(0)
 await page.screenshot({path:'evidence/consulta-desktop.png',fullPage:true,animations:'disabled'})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/consulta-mobile.png',fullPage:true,animations:'disabled'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('consulta lleva criterios a reserva y abandonar los descarta',async({page})=>{
 await login(page)
 await page.getByRole('link',{name:'Disponibilidad',exact:true}).click()
 await page.getByRole('button',{name:'Esporádica',exact:true}).click()
 await page.getByLabel('Cantidad de alumnos prevista').fill('35')
 await page.getByLabel('Proyector',{exact:true}).check()
 await page.getByRole('button',{name:'Buscar aulas'}).click()
 await page.getByRole('button',{name:'Preparar reserva'}).click()
 await expect(page.getByRole('heading',{name:'Nueva reserva esporádica'})).toBeVisible()
 await expect(page.getByLabel('Cantidad de alumnos prevista')).toHaveValue('35')
 await expect(page.getByLabel('Proyector',{exact:true})).toBeChecked()
 await page.getByRole('button',{name:'Salir',exact:true}).click()
 await page.getByRole('button',{name:'Nueva reserva'}).click()
 await expect(page.getByRole('heading',{name:'Nueva reserva periódica'})).toBeVisible()
 await expect(page.getByLabel('Cantidad de alumnos prevista')).toHaveValue('30')
})
test('listados por día y curso filtran e invocan impresión',async({page})=>{
 await login(page)
 await page.getByRole('link',{name:'Reservas',exact:true}).click()
 await expect(page.locator('.screen-list tbody tr')).toHaveCount(4)
 await page.screenshot({path:'evidence/listado-desktop.png',fullPage:true,animations:'disabled'})
 await page.getByLabel('Tipo del listado').selectOption('Multimedios')
 await expect(page.locator('.screen-list tbody tr')).toHaveCount(2)
 await page.evaluate(()=>{window.print=()=>{document.body.dataset.printed='yes'}})
 await page.getByRole('button',{name:'Imprimir listado diario'}).click()
 await expect(page.locator('body')).toHaveAttribute('data-printed','yes')
 await page.getByLabel('Estado del listado').selectOption('cancelled')
 await expect(page.getByText('No hay reservas para estos filtros.')).toBeVisible()
 await page.getByLabel('Estado del listado').selectOption('active')
 await page.getByLabel('Tipo del listado').selectOption('')
 await page.getByRole('button',{name:'Por curso',exact:true}).click()
 await expect(page.getByRole('button',{name:'Imprimir listado diario'})).toHaveCount(0)
 await page.getByLabel('Curso del listado').selectOption('003-A-2026')
 await expect(page.locator('.screen-list tbody tr')).toHaveCount(1)
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/listado-mobile.png',fullPage:true,animations:'disabled'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('agenda semanal conserva filtros y permite volver al día en móvil',async({page})=>{
 await login(page)
 await page.getByRole('button',{name:'Semana',exact:true}).click()
 await expect(page.getByRole('heading',{name:/Semana del 14/})).toBeVisible()
 await expect(page.locator('.week-day')).toHaveCount(5)
 await expect(page.locator('.week-booking')).toHaveCount(4)
 await page.screenshot({path:'evidence/semana-desktop.png',fullPage:true,animations:'disabled'})
 await page.getByLabel('Filtrar tipo').selectOption('Multimedios')
 await expect(page.locator('.week-booking')).toHaveCount(2)
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/semana-mobile.png',fullPage:true,animations:'disabled'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Ver día',exact:true}).first().click()
 await expect(page.getByRole('button',{name:'Semana',exact:true})).toBeVisible()
 await expect(page.getByLabel('Filtrar tipo')).toHaveValue('Multimedios')
 await page.getByLabel('Fecha de agenda').fill('2026-10-12')
 await expect(page.getByRole('status')).toContainText('Fecha no lectiva')
})

test('cancelación con motivo libera agenda y conserva historial', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: /Historia/ }).first().click()
  await page.getByRole('button', { name: 'Cancelar clases', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Confirmar cancelación' })).toBeDisabled()
  await page.getByRole('button', { name: /Todas las futuras/ }).click()
  await page.getByLabel('Motivo de cancelación').fill('Jornada de capacitación docente.')
  await page.screenshot({ path: 'evidence/cancelacion-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/cancelacion-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Confirmar cancelación' }).click()
  await expect(page.getByRole('status')).toContainText('Se canceló 1 clase')
  await expect(page.getByText('R-001 · CANCELADA')).toBeVisible()
  await expect(page.getByText(/Motivo: Jornada/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Cancelar clases', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Menú', exact: true }).click()
  await page.getByRole('link', { name: 'Agenda', exact: true }).click()
  await expect(page.getByRole('button', { name: /Historia/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Menú', exact: true }).click()
  await page.getByRole('link', { name: 'Reservas', exact: true }).click()
  await page.getByLabel('Estado del listado', { exact: true }).selectOption('cancelled')
  await expect(page.getByRole('button', { name: /Historia/ })).toBeVisible()
})

test('cambio de aula periódico actualiza los doce lunes juntos', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await page.getByRole('group', { name: /Lunes/ }).getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio', { name: /Aula 105/ }).check()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await page.getByRole('button', { name: 'Ver detalle' }).click()
  await page.getByRole('button', { name: 'Cambiar aula', exact: true }).click()
  await page.getByRole('radio', { name: /Aula 301/ }).check()
  await page.screenshot({ path: 'evidence/cambio-aula-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/cambio-aula-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Guardar cambio de aula' }).click()
  await expect(page.getByRole('status')).toContainText('Cambio de aula guardado')
  await expect(page.getByText('Aula 301', { exact: true })).toHaveCount(12)
  await expect(page.getByText('Aula 105', { exact: true })).toHaveCount(14)
  await page.getByRole('button', { name: 'Cancelar clases', exact: true }).click()
  await page.getByRole('button', { name: /Todas las futuras/ }).click()
  await page.getByLabel('Motivo de cancelación').fill('Fin de actividad')
  await page.getByRole('button', { name: 'Confirmar cancelación' }).click()
  await expect(page.getByRole('heading', { name: 'Historial de cambios' })).toHaveCount(1)
})

test('reprogramar conserva aula y pertenencia al patrón original', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await page.getByRole('group', { name: /Lunes/ }).getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio', { name: /Aula 105/ }).check()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await page.getByRole('button', { name: 'Ver detalle' }).click()
  await page.getByRole('button', { name: 'Reprogramar clases', exact: true }).click()
  await page.getByRole('checkbox').first().check()
  await page.getByLabel('Nueva fecha', { exact: true }).fill('2026-09-15')
  await page.getByRole('button', { name: 'Revisar reprogramación' }).click()
  await page.screenshot({ path: 'evidence/reprogramacion-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/reprogramacion-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Guardar reprogramación' }).click()
  await expect(page.getByRole('status')).toContainText('Reprogramación guardada')
  await expect(page.getByText('15 de septiembre de 2026', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cambiar aula', exact: true }).click()
  await page.getByRole('radio', { name: /Aula 301/ }).check()
  await page.getByRole('button', { name: 'Guardar cambio de aula' }).click()
  await expect(page.getByText('Aula 301', { exact: true })).toHaveCount(12)
})

test('editar datos revalida aulas y actualiza curso y contacto', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: /Física I/ }).first().click()
  await page.getByRole('button', { name: 'Modificar datos' }).click()
  await page.getByLabel('Alumnos previstos', { exact: true }).fill('41')
  await page.getByRole('button', { name: 'Guardar datos' }).click()
  await expect(page.getByRole('alert')).toContainText('Aula 105')
  await page.getByLabel('Alumnos previstos', { exact: true }).fill('30')
  await page.getByLabel('Curso', { exact: true }).selectOption('001-A-2026')
  await page.getByLabel('Docente', { exact: true }).selectOption('Laura Gómez')
  await page.getByLabel('Proyector', { exact: true }).check()
  await page.screenshot({ path: 'evidence/datos-reserva-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/datos-reserva-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Guardar datos' }).click()
  await expect(page.getByRole('status')).toContainText('Datos de la reserva actualizados')
  await expect(page.getByRole('heading', { name: 'Matemática I', exact: true })).toBeVisible()
  await expect(page.getByText('Aula 105', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('inventario protege reservas e integra nuevas aulas a disponibilidad', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Aulas', exact: true }).click()
  await page.getByRole('button', { name: 'Editar 105', exact: true }).click()
  await page.getByLabel('Capacidad (personas)', { exact: true }).fill('30')
  await page.getByRole('button', { name: 'Guardar aula' }).click()
  await expect(page.getByRole('alert')).toContainText('R-002')
  await page.getByRole('button', { name: 'Nueva aula', exact: true }).click()
  await page.getByLabel('Identificador', { exact: true }).fill('S01')
  await page.getByLabel('Tipo de aula', { exact: true }).selectOption('Multimedios')
  await page.getByLabel('Ubicación / edificio', { exact: true }).fill('Edificio B')
  await page.getByLabel('Piso', { exact: true }).fill('-1')
  await page.screenshot({ path: 'evidence/aulas-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/aulas-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Guardar aula' }).click()
  await expect(page.getByRole('status')).toContainText('Aula guardada')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('link', { name: 'Agenda', exact: true }).click()
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(page.getByRole('group', { name: /Lunes/ }).getByRole('radio', { name: /Aula S01/ })).toBeVisible()
  await page.getByRole('link', { name: 'Aulas', exact: true }).click()
  await page.getByRole('button', { name: 'Editar S01', exact: true }).click()
  await page.getByLabel('Estado del aula', { exact: true }).selectOption('Mantenimiento')
  await page.getByRole('button', { name: 'Guardar aula' }).click()
  await page.getByRole('link', { name: 'Agenda', exact: true }).click()
  await expect(page.getByText(/Aulas no reservables actualmente/)).toContainText('S01')
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(page.getByRole('radio', { name: /Aula S01/ })).toHaveCount(0)
})

test('administrador gestiona cuenta y contraseña conservando último admin', async ({ page }) => {
  await login(page, 'admin')
  await page.getByRole('link', { name: 'Administración', exact: true }).click()
  await page.getByRole('button', { name: 'Editar admin@demo.local' }).click()
  await page.getByLabel('Estado de cuenta', { exact: true }).selectOption('inactive')
  await page.getByRole('button', { name: 'Guardar cuenta' }).click()
  await expect(page.getByRole('alert')).toContainText('administrador activo')
  await page.getByRole('button', { name: 'Nueva cuenta' }).click()
  await page.getByLabel('Nombre', { exact: true }).fill('Mario')
  await page.getByLabel('Apellido', { exact: true }).fill('Prueba')
  await page.getByLabel('Correo de acceso', { exact: true }).fill('mario@example.test')
  await page.getByLabel('Rol de cuenta', { exact: true }).selectOption('Docente')
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('Primera123')
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill('Primera123')
  await page.screenshot({ path: 'evidence/cuentas-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Guardar cuenta' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'evidence/cuentas-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Guardar cuenta' }).click()
  await page.getByRole('button', { name: 'Editar mario@example.test' }).click()
  await page.getByRole('button', { name: 'Establecer contraseña', exact: true }).click()
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('Segunda123')
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill('Segunda123')
  await page.getByRole('button', { name: 'Guardar contraseña' }).click()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await page.getByLabel('Correo electrónico').fill('mario@example.test')
  await page.getByLabel('Contraseña', { exact: true }).fill('Primera123')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('no son correctos')
  await page.getByLabel('Contraseña', { exact: true }).fill('Segunda123')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Nueva reserva' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Administración' })).toHaveCount(0)
})

test('calendario extiende serie y recupera feriado de forma conjunta', async ({ page }) => {
  await login(page, 'admin')
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await page.getByRole('group', { name: /Lunes/ }).getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio', { name: /Aula 105/ }).check()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await page.getByRole('link', { name: 'Administración', exact: true }).click()
  await page.getByRole('link', { name: 'Calendario académico', exact: true }).click()
  await page.getByLabel('Nueva fecha no lectiva', { exact: true }).fill('2026-09-14')
  await page.getByLabel('Descripción nueva', { exact: true }).fill('Cierre de prueba')
  await page.getByRole('button', { name: 'Agregar fecha', exact: true }).click()
  await page.getByRole('button', { name: 'Revisar impacto' }).click()
  await expect(page.getByRole('alert')).toContainText('afecta')
  await page.getByRole('button', { name: 'Descartar cambios' }).click()
  await page.getByRole('button', { name: 'Quitar 2026-10-12' }).click()
  await page.getByLabel('Fin 2', { exact: true }).fill('2026-12-23')
  await page.getByRole('button', { name: 'Revisar impacto' }).click()
  await expect(page.getByText(/Clases nuevas: 3/)).toBeVisible()
  await page.screenshot({ path: 'evidence/calendario-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Confirmar cambio de calendario' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'evidence/calendario-mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Confirmar cambio de calendario' }).click()
  await expect(page.getByRole('status')).toContainText('Calendario y clases actualizados')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('link', { name: 'Agenda', exact: true }).click()
  await page.getByRole('button', { name: /Matemática I/ }).first().click()
  await expect(page.getByRole('heading', { name: '29 clases registradas' })).toBeVisible()
})

test('año nuevo requiere cuatrimestres y permite reservar con curso propio', async ({ page }) => {
 await login(page,'admin')
 await page.getByRole('link',{name:'Administración',exact:true}).click()
 await page.getByRole('link',{name:'Calendario académico',exact:true}).click()
 await page.getByLabel('Estado del año',{exact:true}).selectOption('Cerrado')
 await page.getByRole('button',{name:'Revisar impacto'}).click()
 await expect(page.getByRole('alert')).toContainText('futuras')
 await page.getByLabel('Nuevo año',{exact:true}).fill('2027')
 await page.getByRole('button',{name:'Crear año',exact:true}).click()
 await page.getByLabel('Inicio 1',{exact:true}).fill('2027-03-08')
 await page.getByLabel('Fin 1',{exact:true}).fill('2027-07-02')
 await page.getByRole('button',{name:'Revisar impacto'}).click()
 await page.getByRole('button',{name:'Confirmar cambio de calendario'}).click()
 await page.getByLabel('Inicio 2',{exact:true}).fill('2027-09-13')
 await page.getByLabel('Fin 2',{exact:true}).fill('2027-12-17')
 await page.getByLabel('Estado del año',{exact:true}).selectOption('Habilitado')
 await page.getByRole('button',{name:'Revisar impacto'}).click()
 await page.getByRole('button',{name:'Confirmar cambio de calendario'}).click()
 await page.screenshot({path:'evidence/anios-desktop.png',fullPage:true,animations:'disabled'})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/anios-mobile.png',fullPage:true,animations:'disabled'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.setViewportSize({width:1440,height:1000})
 await page.getByRole('link',{name:'Agenda',exact:true}).click()
 await page.getByRole('button',{name:'Nueva reserva'}).click()
 await page.getByLabel('Año de la reserva',{exact:true}).selectOption('2027')
 await page.getByRole('button',{name:'Crear curso',exact:true}).click()
 await page.getByLabel('Nombre de materia',{exact:true}).fill('Matemática I')
 await page.getByLabel('Comisión',{exact:true}).fill('A')
 await page.getByRole('button',{name:'Guardar curso y seleccionar'}).click()
 await page.getByRole('button',{name:'Buscar aulas'}).click()
 await page.getByRole('group',{name:/Lunes/}).getByRole('radio').first().check()
 await page.getByRole('group',{name:/Miércoles/}).getByRole('radio').first().check()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await page.getByRole('button',{name:'Confirmar reserva'}).click()
 await expect(page.getByRole('heading',{name:'Reserva confirmada'})).toBeVisible()
 await page.getByRole('button',{name:'Ver detalle'}).click()
 await expect(page.getByText(/001-A-2027/).first()).toBeVisible()
 await page.getByRole('link',{name:'Disponibilidad',exact:true}).click()
 await page.getByLabel('Año de la reserva',{exact:true}).selectOption('2027')
 await page.getByRole('button',{name:'Buscar aulas'}).click()
 await page.getByRole('button',{name:'Preparar reserva'}).click()
 await expect(page.getByLabel('Curso',{exact:true})).toHaveValue('001-A-2027')

})

test('indicadores diarios reflejan reservas, filtros y cero sin acceso docente', async ({ page }) => {
 const errors: string[]=[]; page.on('pageerror',e=>errors.push(e.message))
 await login(page)
 await page.getByRole('link',{name:'Indicadores',exact:true}).click()
 await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('6,5 h')
 await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('6,8 %')
 await expect(page.getByText('252',{exact:true})).toBeVisible()
 await expect(page.locator('canvas')).toHaveCount(2)
 await expect(page.getByRole('heading',{name:'Clases simultáneas',exact:true})).toBeVisible()
 await page.screenshot({path:'evidence/indicadores-dia-desktop.png',fullPage:true,animations:'disabled'})
 await page.setViewportSize({width:390,height:844})
 await page.getByText('Ver las 32 franjas y sus valores').scrollIntoViewIfNeeded()
 await page.screenshot({path:'evidence/indicadores-dia-mobile.png',fullPage:true,animations:'disabled'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByText('Ver las 32 franjas y sus valores').click()
 await expect(page.locator('.metric-values tbody tr')).toHaveCount(32)
 await page.getByLabel('Aula',{exact:true}).selectOption('Lab 2')
 await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('12,5 %')
 await page.getByLabel('Día',{exact:true}).fill('2026-09-15')
 await expect(page.getByRole('region',{name:'Resumen diario'})).toContainText('0 %')
 await page.getByLabel('Día',{exact:true}).fill('2026-10-12')
 await expect(page.getByText('Sin horas habilitadas',{exact:true})).toBeVisible()
 expect(errors).toEqual([])
 await login(page,'docente')
 await page.evaluate(()=>{ history.pushState({},'', '/indicadores'); dispatchEvent(new PopStateEvent('popstate')) })
 await expect(page).toHaveURL(/agenda/)
})

test('semana típica muestra fechas, franjas accesibles y rangos sin datos', async ({ page }) => {
 await login(page)
 await page.getByRole('link',{name:'Indicadores',exact:true}).click()
 await page.getByRole('button',{name:'Semana típica',exact:true}).click()
 await expect(page.getByRole('region',{name:'Resumen del rango'})).toContainText('6,5 h')
 await expect(page.locator('.heat-cell')).toHaveCount(160)
 await expect(page.locator('.heat-table tbody tr').first()).toContainText('12 fechas')
 const cell=page.getByRole('button',{name:/Lunes 14:00–14:30:/})
 await cell.focus()
 await expect(page.locator('.heat-selection')).toContainText('8 alumnos previstos')
 await expect(page.locator('.heat-selection')).toContainText('12 fechas aportantes')
 await page.screenshot({path:'evidence/indicadores-semana-desktop.png',fullPage:true,animations:'disabled'})
 await page.setViewportSize({width:390,height:844})
 await page.getByRole('heading',{name:'Comparación entre días'}).scrollIntoViewIfNeeded()
 await page.screenshot({path:'evidence/indicadores-semana-mobile.png',fullPage:true,animations:'disabled'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByLabel('Período',{exact:true}).selectOption('custom')
 await page.getByLabel('Desde',{exact:true}).fill('2026-10-12')
 await page.getByLabel('Hasta',{exact:true}).fill('2026-10-12')
 await expect(page.getByText('Sin datos aplicables de apertura para la consulta.')).toBeVisible()
 await page.getByRole('button',{name:/Lunes 14:00–14:30:/}).click()
 await expect(page.locator('.heat-selection')).toContainText('Sin datos aplicables')
 await page.getByLabel('Desde',{exact:true}).fill('2026-10-13')
 await expect(page.getByRole('alert')).toContainText('rango válido')
 await expect(page.locator('.heat-cell')).toHaveCount(0)
})
