import { test, expect } from '@playwright/test'
async function login(page: import('@playwright/test').Page, role = 'bedel') {
  await page.goto('/')
  await page.getByLabel('Correo electrónico').fill(`${role}@demo.local`)
  await page.getByLabel('Contraseña', { exact: true }).fill('Aulas2026')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
}
test('reserva periódica completa y lectura desde agenda', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await login(page)
  await page.screenshot({ path: 'evidence/agenda-desktop.png' })
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.screenshot({ path: 'evidence/reserva-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  const monday = page.getByRole('group', { name: /Lunes/ })
  await expect(monday.getByText('Aula 105', { exact: true })).toHaveCount(0)
  await monday.getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Volver', exact: true }).click()
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(monday.getByRole('radio').first()).toBeChecked()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Volver', exact: true }).click()
  await expect(monday.getByRole('radio').first()).toBeChecked()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await expect(page.getByRole('heading', { name: 'Reserva confirmada' })).toBeVisible()
  await page.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByRole('heading', { name: '26 clases registradas' })).toBeVisible()
  await page.getByRole('link', { name: 'Agenda', exact: true }).click()
  await expect(page.getByRole('button', { name: /Matemática I/ }).first()).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/agenda-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
test('docente consulta y no accede a nueva reserva', async ({ page }) => {
  await login(page, 'docente')
  await expect(page.getByRole('button', { name: 'Nueva reserva' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Reservas', exact: true }).click()
  await page.getByRole('button', { name: /Historia/ }).click()
  await expect(page.getByRole('heading', { name: 'Historia', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page.getByRole('heading', { name: 'Ingresar' })).toBeVisible()
})
test('formulario en móvil y tablet no desborda', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  for (const width of [390, 768]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/reserva-mobile.png', fullPage: true })
})
test('excluir una fecha mantiene aula por patrón y guarda 25 clases', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByText('Revisar fechas y exclusiones', { exact: true }).click()
  await page.getByLabel('14 de septiembre de 2026 · 14:00–16:00', { exact: true }).uncheck()
  await expect(page.getByText('14 de septiembre de 2026 · Exclusión manual')).toBeVisible()
  await page.screenshot({ path: 'evidence/exclusiones-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'evidence/exclusiones-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await page.getByRole('group', { name: /Lunes/ }).getByRole('radio').first().check()
  await page.getByRole('group', { name: /Miércoles/ }).getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar reserva' }).click()
  await page.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByRole('heading', { name: '25 clases registradas' })).toBeVisible()
})
test('período terminado bloquea el avance sin borrar la preparación', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nueva reserva' }).click()
  await page.getByLabel('Período', { exact: true }).selectOption('first')
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(page.getByRole('alert')).toContainText('al menos una clase futura')
  await page.getByLabel('Período', { exact: true }).selectOption('annual')
  await page.getByRole('button', { name: 'Buscar aulas' }).click()
  await expect(page.getByRole('heading', { name: 'Un aula para cada día semanal' })).toBeVisible()
})
test('conflictos son informativos y no permiten elegir el aula ocupada', async ({ page }) => {
 await login(page)
 await page.getByRole('button', { name: 'Nueva reserva' }).click()
 await page.getByLabel('Tipo de aula').selectOption('General')
 await page.getByRole('button', { name: 'Buscar aulas' }).click()
 const monday = page.getByRole('group', {name:/Lunes/})
 await expect(monday.getByRole('heading',{name:'Requieren resolver conflictos'})).toBeVisible()
 await expect(monday.getByRole('radio')).toHaveCount(0)
 await monday.getByText('Ver reservas y contactos').click()
 await expect(monday.getByText(/sofia.paz@example.test/)).toBeVisible()
 await expect(monday.getByText(/bedel@demo.local/)).toBeVisible()
 await page.screenshot({path:'evidence/conflictos-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'evidence/conflictos-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('group',{name:/Miércoles/}).getByRole('radio').first().check()
 await expect(page.getByRole('button',{name:'Revisar reserva'})).toBeDisabled()
 await expect(page.getByRole('button',{name:'Confirmar reserva'})).toHaveCount(0)
})

test('conservar cuarta aula al contraer y volver de revisión', async ({ page }) => {
 await login(page)
 await page.getByRole('button', {name:'Nueva reserva'}).click()
 await page.getByRole('button', {name:'Buscar aulas'}).click()
 await page.getByRole('group',{name:/Lunes/}).getByRole('radio').first().check()
 const wed = page.getByRole('group',{name:/Miércoles/})
 await wed.getByRole('button',{name:'Ver todas (4)'}).click()
 await wed.getByRole('radio',{name:/Aula 204/}).check()
 await wed.getByRole('button',{name:'Ver primeras tres'}).click()
 await expect(wed.getByRole('radio',{name:/Aula 204/})).toBeChecked()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await page.getByRole('button',{name:'Volver',exact:true}).click()
 await expect(wed.getByRole('radio',{name:/Aula 204/})).toBeChecked()
 await page.getByRole('button',{name:'Revisar reserva'}).click()
 await expect(page.getByRole('button',{name:'Confirmar reserva'})).toBeVisible()
})
