import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('errores enfocan el resumen y permiten corregir el campo con teclado',async({page})=>{
 await page.goto('/');await page.getByLabel('Correo electrónico').fill('admin@demo.local');await page.getByLabel('Contraseña',{exact:true}).fill('equivocada');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page.getByRole('alert')).toBeFocused();await page.keyboard.press('Tab');await page.keyboard.press('Enter');await expect(page.getByLabel('Correo electrónico')).toBeFocused();
 await page.getByLabel('Contraseña',{exact:true}).fill('Aulas2026');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await page.getByRole('link',{name:'Administración',exact:true}).click();await page.getByRole('button',{name:'Nueva cuenta',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('María');await page.getByLabel('Apellido',{exact:true}).fill('Prueba');await page.getByLabel('Correo de acceso').fill('maria@example.test');await page.getByLabel('Nueva contraseña',{exact:true}).fill('Nueva2026');await page.getByLabel('Confirmar contraseña',{exact:true}).fill('Distinta2026');await page.getByRole('button',{name:'Guardar cuenta'}).click();
 await expect(page.getByRole('alert')).toBeFocused();await expect(page.getByLabel('Confirmar contraseña',{exact:true})).toHaveAttribute('aria-invalid','true');await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Revisar confirmación de contraseña'})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByLabel('Confirmar contraseña',{exact:true})).toBeFocused();
 await page.screenshot({path:'evidence/error-campo-desktop.png'});await page.setViewportSize({width:390,height:844});await page.getByRole('alert').scrollIntoViewIfNeeded();await page.screenshot({path:'evidence/error-campo-mobile.png'});expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze()).violations).toEqual([]);
 await page.keyboard.press('ControlOrMeta+A');await page.keyboard.type('Nueva2026');await page.getByRole('button',{name:'Guardar cuenta'}).click();await expect(page.getByRole('status')).toContainText('Cuenta guardada');
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('link',{name:'Aulas',exact:true}).click();await page.getByRole('button',{name:'Nueva aula',exact:true}).click();await page.getByLabel('Identificador',{exact:true}).fill('105');await page.getByLabel('Ubicación / edificio',{exact:true}).fill('Edificio A');await page.getByRole('button',{name:'Guardar aula'}).click();await expect(page.getByRole('alert')).toBeFocused();await page.keyboard.press('Tab');await page.keyboard.press('Enter');await expect(page.getByLabel('Identificador',{exact:true})).toBeFocused();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.type('900');await page.getByRole('button',{name:'Guardar aula'}).click();await expect(page.getByRole('status').filter({hasText:'Aula guardada'})).toBeVisible();
});

test('repetir un error de curso vuelve a enfocar el mensaje y enlaza sus campos',async({page})=>{
 await page.goto('/');await page.getByLabel('Correo electrónico').fill('bedel@demo.local');await page.getByLabel('Contraseña',{exact:true}).fill('Aulas2026');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await page.getByRole('button',{name:'Nueva reserva',exact:true}).click();await page.getByRole('button',{name:'Crear curso',exact:true}).click();
 for(let i=0;i<2;i++){await page.getByRole('button',{name:'Guardar curso y seleccionar'}).click();await expect(page.getByRole('alert')).toBeFocused();}
 await page.keyboard.press('Tab');await page.keyboard.press('Enter');await expect(page.getByLabel('Nombre de materia')).toBeFocused();
});
